name: Download Umittube

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests urllib3
      - run: python umittube.py
        env:
          ENCRYPTED_PLAYLIST_URL: ${{ secrets.ENCRYPTED_PLAYLIST_URL }}
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add Umittube/
          git commit -m "update" || exit 0
          git push
